spring.application.name=NauJava
app.name=To-Do List
app.version=1.0.0
management.endpoints.web.exposure.include=*
spring.datasource.url=jdbc:postgresql://localhost:5432/to-do-list
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
